# Website details
name: "Jordan Tully"
description: "Musings of a Noob Game Dev"
email: "jordantully@fastmail.fm"
author: "Jordan Tully"
lang: "english"
locale: "english"

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: America/Halifax
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: http://jtully.ca

# Includes
addthisId: "58f91d479341a5c7"
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"